### ISSUE TITLE
Enhanced Parsed Request Body (JSON)

### ISSUE THREAD

**Issue by kerrishotts** [luckymarmot/Paw-Issues#14]
I've been using PAW to test my API, and it's absolutely fantastic. I've been trying to make it behave closer to how my app would, so rather than hard-code the API paths (say, `/people/2`), the API returns a template href like `/person/{personId}` in the response. I would then love to be able to use this as part of the URL for the next request. (I can, but only if the response doesn't include the template portion. For now, I can work around this with an additional href in the response, but it'd be nice to avoid having to do so).

It would be nice to have either:

* select a portion of the value (say, `substr(0,7)` would get me the path I want)
* or actually support filling in the `{...}` values akin to the query parameter editing you have now

I'd wager the first is easiest, but the second would be really quite nice.

**Comment by drewish** [comment]
Does https://github.com/luckymarmot/Paw-SubstringDynamicValue fulfill this?

**Comment by mittsh** [comment]
Yes, the Substring DV + Regexp DV will solve these requirements. Thanks for pointing this out @drewish! Closing.
