### ISSUE TITLE
Global Dynamic Variables

### ISSUE THREAD

**Issue by kerrishotts** [luckymarmot/Paw-Issues#16]
I'm not entirely sure that this would be the best name for the feature, but let me explain what I'd like:

I have an API that sends new tokens on each request. The next request to the API must use that token, and it in turn receives another token, and so on. 

Right now, I have Paw set up to pull this token from a specific request, but this then couples the requests together -- it'd be nice instead to have a less specific context where I could dump the token, and then have any other request use it. Furthermore, should another request respond with the same key path, it'd be nice to have Paw update this context, and so on.

Something like this:

    Global Dynamic Variable: token
        Parsed Response (JSON)
            keypath: next-token
    
    Any request:
        Headers:
            x-token: [Global Dynamic Variable: token]
        Response:
            { next-token: .... }

When the `next-token` response is received from any request, the global dynamic variable would then be updated such that further requests would receive the new value.

Right now, I handle this by following requests in specific orders so that they copy the value from the prior request. But it'd be nice not to be quite as tightly coupled all the time.

Ok -- final issue for today! Your app is amazing, and I absolutely love it -- this would just put me over the moon! :-)

**Comment by ndizazzo** [comment]
Hey @mittsh I'm resurrecting this issue, to sort of piggyback on the line of thought.

Suppose an API returns a token in a response. Would it be possible to pick out a field in that response, and set one of the variables @kerrishotts would have set up in in one of her domains?

This would allow you to authenticate with an API, and get an authorization token back that you can put in subsequent request headers., That would *TOTALLY* rock.

**Comment by ndizazzo** [comment]
@kerrishotts Did you ever find out how to set the value of a variable when you receive a response?

**Comment by ndizazzo** [comment]
Nevermind! I figured it out. For those also looking:

1. Make sure you get a successful (20x) response from an endpoint.
2. Go to the response view for the exchange
3. Right click the field (I'm using JSON) name you want as a dynamic value
4. Click 'copy as response body dynamic value'.
5. Paste that into your environment/domain config value column.

**Comment by mittsh** [comment]
Hey @ndizazzo sorry for getting back late. Happy you figured that out, and thanks for the step-by-step instructions!

You can also go to the environments and in the value field right-click and pick Response > Response parsed body:

![image](https://cloud.githubusercontent.com/assets/1319906/6880541/52179a7c-d537-11e4-9df7-10f077e3d942.png)

And configure the request + path manually:

![image](https://cloud.githubusercontent.com/assets/1319906/6880545/6da29aee-d537-11e4-980b-eb59c40c69c6.png)
