### ISSUE TITLE
Feature Request: auto-run dependent requests

### ISSUE THREAD

**Issue by winowa** [luckymarmot/Paw-Issues#17]
## Justification

When taking advantage of "Copy as Dynamic Value", for API endpoints that require multiple previous calls before they can run successfully (e.g. a `sign-in` call followed by the creation of a parent entity might need to be run before creating a leaf entity). Instead of having to find all of those dependencies manually and run them, it would be nice if Paw had a new option to run all of them with a single command. 
## Suggestion

CMD+RETURN sends the current request. CMD+OPTION+RETURN could follow the dependencies from all "Copy as Dynamic Value" pasted values and send all required requests recursively in dependency order before sending the current request.

**Comment by ChristianPraiss** [comment]
Hey guys, any news on this one? :)

**Comment by mittsh** [comment]
No not much progress on this side… though we have the idea, it's a very nice one! I'll push it up for the next version! @ChristianPraiss

**Comment by wilmoore** [comment]
I love everything about paw so far; except, the fact that "dynamic" values based on an http response behaves in a surprising way. As it is currently, "dynamic" values based on an http request are semi-static in that they are only dynamic as of the last time the request was executed.

This discrepancy means that it is not possible to execute a request that depends on another request (e.g. request an oauth2 access token) in one environment then switch to another environment and have it work as expected as the dependent request values will be bound to the previous environment.

**Comment by ChristianPraiss** [comment]
This could also be quite useful for creating realistic load-test scenarios. You could build a chain of requests like it would come from the client and then generate templates for load-testing tools like BlazeMeter. This would combine the comfort of using Paw's awesome UI with the importance of creating tests, as both could be created at the same time. There's a huge potential for saving time and resources here! I'd love to hear your opinion on that!

**Comment by hishnash** [comment]
Im closing this as we added send dependent request in the latest release: 3.0.14  press ⇧⌘⏎
