### ISSUE TITLE
Save the selected environment as well

### ISSUE THREAD

**Issue by kiliankoe** [luckymarmot/Paw-Issues#22]
Hi Micha,

I'm using the environment in Paw to save the base_url for my requests for different environments. I frequently find myself opening up Paw and then first having to switch the environment. It'd be great if the selected environment were saved in the .paw file as well.

![screen shot 2014-12-15 at 10 22 18](https://cloud.githubusercontent.com/assets/2625584/5433261/dd43f412-8445-11e4-9a02-2811b6a2b361.png)

**Comment by hishnash** [comment]
@kiliankoe sorry about the late reply on this. In paw 2.2.6 the last used environment is persisted.
