### ISSUE TITLE
duplicate a request, then try to change url of the duplicate and both requests change

### ISSUE THREAD

**Issue by dwolfhub** [luckymarmot/Paw-Issues#24]
osx 10.10.2

**Comment by hishnash** [comment]
@dwolfhub can you test this again on the latest release 2.2.6 i cant reproduce it

**Comment by mittsh** [comment]
@dwolfhub @hishnash I'm very positive that this bug have been fixed a while ago (sorry for the late answer). Closing this issue. @dwolfhub please let us know if this still happens to you...
