### ISSUE TITLE
Allow setting DynamicValueInput default value

### ISSUE THREAD

**Issue by joshuajabbour** [luckymarmot/Paw-Issues#25]
It would be great to be able to set a default value for DynamicValueInput when creating extensions. Maybe as a fourth parameter?

**Comment by Hessmjr** [comment]
I'm assuming you mean a default a dynamic user input parameter?  If so then I completely agree it would be nice to have that functionality built into the program.  bump

**Comment by drewish** [comment]
This can be closed now. The options fourth param is now an object with a `defaultValue`. https://paw.cloud/docs/extensions/input-fields

**Comment by mittsh** [comment]
Correct, thanks! Closing.
