### ISSUE TITLE
Add ability to enable/disable URL Params

### ISSUE THREAD

**Issue by joshuajabbour** [luckymarmot/Paw-Issues#26]
The Headers tab has checkboxes for each header, which give you the wonderful ability to enable headers for individual requests on-the-fly. I wish the URL Params tab had the same feature. This way I could create rows for all accepted parameters, but only send the ones I want when testing the actual request (basically it would allow me to create a template for the request).

**Comment by mittsh** [comment]
@joshuajabbour real apologizes for the long delay... enable/disable URL params is really something we want to add for a long long time, and as other features were more prioritized, we still didn't do it, but that's definitively in our minds...

**Comment by Hessmjr** [comment]
Very surprising this isn't an option already especially since other values have the ability already.  Would definitely like to see this implemented as well.

**Comment by acwright** [comment]
+1

**Comment by MrMaz** [comment]
+1 from me too. This is critical for REST development since doing a `find` or `search` is always supposed to use the GET method.

**Comment by zdrummond** [comment]
@mittsh When do you think we can have this. Super critical for setting up a PAW file to play with an API.

**Comment by hishnash** [comment]
@zdrummond @MrMaz @acwright @hessmjr Good news I can confirm this is working and ready to come in the next release, we are aiming for end of this month. 

The reason this has taken so long is to implement it in a nice stable manner required a significant data model refactoring. luckily in our next release we needed to do this for a major upcoming feature so we were able to sneak this one in on the side.

**Comment by zdrummond** [comment]
That is great! I look forward to it

**Comment by MrMaz** [comment]
Looks good in v3. Thank you! <3

**Comment by joshuajabbour** [comment]
This now exists in v3. Yay!
