### ISSUE TITLE
Add ability to nest environment variables

### ISSUE THREAD

**Issue by joshuajabbour** [luckymarmot/Paw-Issues#27]
It would be great if environment variables could contain other environment variables. Nested vars would allow for such greater flexibility in setting up environments.

**Comment by joshuajabbour** [comment]
This might be a different feature request, but another use would be allowing Dynamic Values inside of Environment Variables. So that I could have an `article_id` variable, and it would dynamically select a value...

**Comment by hishnash** [comment]
@joshuajabbour `Dynamic Values` usable inside environment variables.

**Comment by mittsh** [comment]
@hishnash yes, I think it wasn't the case for a few versions (due to a bug), it's most surely resolved now...
