### ISSUE TITLE
Add request import from Charles

### ISSUE THREAD

**Issue by mittsh** [luckymarmot/Paw-Issues#29]

**Comment by ckozak** [comment]
+1

**Comment by jevgen** [comment]
+1

**Comment by mittsh** [comment]
@ckozak @jevgen Reading over this again, I realized that Charles actually already has the ability to export data to HAR format, and Paw has a [HAR Importer](https://luckymarmot.com/paw/extensions/HARImporter). So it shouldn't be hard to export HAR from Charles, and import the dump into Paw.

**Comment by mittsh** [comment]
We have added a doc article about this: [Import Requests from Charles](https://paw.cloud/docs/import/import-charles). Using HAR format it's easy. Closing.
