### ISSUE TITLE
High CPU usage when editing PAWfile properties

### ISSUE THREAD

**Issue by ndizazzo** [luckymarmot/Paw-Issues#31]
After the last update:

```
Version 2.2.1 (Retail)
Build 47427D (2002001001) | Document Model 7CD917
```

I have been experiencing high CPU usage when PAW is in the foreground while editing properties on a PAWfile. I noticed that input was being delayed as I typed it into the address bar, as well as the HTTP Header property list view.

![screen shot 2015-05-25 at 12 27 55 pm](https://cloud.githubusercontent.com/assets/728690/7799874/0eae12e0-02da-11e5-8d0a-1aa65716caae.png)

This screenshot was taken after about 15 minutes of usage. I closed and restarted the application, re-opened the same file and the problem still occurred.

**Comment by ndizazzo** [comment]
Additionally - here's a screen shot of the energy tab:

![screen shot 2015-05-25 at 1 04 22 pm](https://cloud.githubusercontent.com/assets/728690/7800140/c3e32494-02de-11e5-8759-f9f90894f060.png)

**Comment by mittsh** [comment]
@ndizazzo thanks for reporting this, I'm aware of this bug :( still couldn't exactly reproduce it myself, but I'm working on it. If you have any steps to reproduce this, I'd love to hear more about it. Is it consistently happening? Thanks!

**Comment by ndizazzo** [comment]
I have a fairly large PAWfile  with many levels of organized API folders. I'm collecting a set of APIs into one PAWfile, one folder per API (so that I can share login tokens across each API). 

The group nesting depth is at most 4, but theres about 30 separate API calls in the file, overall. 

I created it using the version before the last one released - and upgraded PAW after I had created the file.

To reproduce the high CPU usage - I don't even have to use the app for it to start happening - the moment I open the file now my usage jumps. If it's helpful, I can forward that along?

**Comment by ndizazzo** [comment]
Thinking about it a little bit more: you would be able to run the app in the profiler and see where the most CPU cycles are being spent if you roll back your development branch to the commit you released 2.2.1 on. 

Is there a quick way to clear request and response data out of my PAWfile? I'd want to do that before sending it over. I'll make sure the issue still happens after clearing out that data, too, to see if it's related to stored request/response data.

**Comment by mittsh** [comment]
@ndizazzo Sorry for the late follow-up. We finally found the problem (there was 2 distinct issues actually), and it's now released in Paw 2.2.2 https://luckymarmot.com/paw/updates/2.2.2
Thanks a lot for your detailed feedback. Let us know if Paw 2.2.2 actually fixed your issue.

**Comment by ndizazzo** [comment]
It's actually still occurring on 2.2.2. It's not nearly as bad - only half the CPU usage compared to before. Get in touch with me via email and I'll send you a PAWfile that might help identify the issue.

**Comment by mittsh** [comment]
Ugh... that's weird. Can you send us details to support@luckymarmot.com please? Thanks much!
