### ISSUE TITLE
Add request import from curl

### ISSUE THREAD

**Issue by yesmeck** [luckymarmot/Paw-Issues#32]

**Comment by mittsh** [comment]
@yesmeck absolutely something we want to add for a while! will push it up in the todo list :)

**Comment by raven** [comment]
+ 1

**Comment by Think7** [comment]
I would pay many much money for this feature...

I spend a lot of time reversing API's and this would be a godsend.

**Comment by hishnash** [comment]
@Think7 @raven @yesmeck could you possibly provide a few examples you would like to import. We will try to add an importer for this soon.

**Comment by minikin** [comment]
@hishnash  for instance 

```
curl -X GET \
  -H "X-Parse-Application-Id: 1111" \
  -H "X-Parse-REST-API-Key: 1111" \
  -G \
  --data-urlencode 'where={
   "playerName": {
     "$nin": [
       "Jonathan Walsh",
       "Dario Wunsch",
       "Shawn Simon"
     ]
   }
  }' \
  --data-urlencode 'order=score,-name' \
  --data-urlencode 'limit=200' \
  --data-urlencode 'skip=400' \
  --data-urlencode 'keys=score,playerName' \
  https://api.parse.com/1/classes/GameScore

```

**Comment by hishnash** [comment]
@minikin thanks i will try to get a prototype for these basic `curl` options. 
Will take a long time to get a curl complete importer, have you seen the man page.

**Comment by Think7** [comment]
The basics alone would save me a ton of time. Host, Header, Query Params, Form Data.

I use CharlesProxy to capture requests and then Paw to debug. CP has some build in features but Paw is nicer to use for this. Especially in cases where you need to modify the request manually to test something.

Example:

```
curl -H "Host: www.forwarderlogic.com" \
-H "Cache-Control: max-age=0" \
-H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" \
-H "Origin: https://www.forwarderlogic.com" \
-H "Upgrade-Insecure-Requests: 1" \
-H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36" \
-H "DNT: 1" \
-H "Referer: https://www.forwarderlogic.com/all/CustomSadCompanyBecauseWeUseThisHorribleSoftware/logonmenu.htm" \
-H "Accept-Language: en-US,en;q=0.8" \
-H "Cookie: BIGipServerwww.forwarderlogic.com_HTTPS=YYYYYYY; XXXXXXX=ZZZZZZZZ; user_start=100100010001111" \
--data "userID=asdasd&password=asdasdasd&action.x=42&action.y=4&action=Log+On" \
--compressed https://www.forwarderlogic.com/scripts/fl.dll/Flogic.exe?33,SadCompanyBecauseWeUseThisHorribleSoftware
```

**Comment by raven** [comment]
In exactly the same boat. Also I have come across a lot of documentation that has cURL commands in it. As mentioned, the basics of host, header, params, body. 

Sent from Outlook

    _____________________________

**Comment by hishnash** [comment]
@raven @Think7 @minikin @yesmeck we know have a cURL importer. You can install it from https://luckymarmot.com/paw/extensions/cURLImporter
and for information and what is supported please see: 
https://github.com/luckymarmot/Paw-cURLImporter

I will close this issue know if you have any issues with the importer please open issues on the Paw-cURLImporter repository.
