### ISSUE TITLE
Receiving 401Unauthorized 

### ISSUE THREAD

**Issue by hessmjr** [luckymarmot/Paw-Issues#33]
I am receiving 401 Unauthorized errors for requests I make daily on Postman and I can't figure out what the difference is or why.  The only thing I've noticed in the requests I'm making and the original ones I used on Postman are the Host according to Paw is lacking the API token ID and I've tried everything I can to get it to recognize the api token in the Host portion of the request.  Ex:

Postman reports host as: {api_token}:@URL/v2/
Paw reports host as: URL/v2/  yet the GET string shows the "{api_token}:" in it

**Comment by hishnash** [comment]
Would it be possible for you to share the file? (postman and or paw)

@Hessmjr we have recently updated out postman importer, it know import Postman environment variables correctly. give this a try if it fixes it.
