### ISSUE TITLE
variable name gets reversed

### ISSUE THREAD

**Issue by windirt** [luckymarmot/Paw-Issues#35]
I'm using El Capitan DP 8，I got reversed variable (dynamic value) name.
![aa](https://cloud.githubusercontent.com/assets/6456747/9709695/d3f210da-5562-11e5-81fd-cfec616ff55c.jpg)

**Comment by mittsh** [comment]
@windirt thanks for reporting it, it's a known issue, a fix will ship today (in a few days for MAS version)

**Comment by windirt** [comment]
Thank you for the fast response.
