### ISSUE TITLE
"\n" in the dynamic value

### ISSUE THREAD

**Issue by windirt** [luckymarmot/Paw-Issues#36]
I'm using Paw to calculate a HMAC SHA1 signature, the input text has many `\n` in it.

the input text is:

	PUT\nODBGOERFMDMzQTczRUY3NUE3NzA5QzdFNUYzMDQxNEM=\ntext/html\nThu, 17 Nov 2005 18:49:58 GMT\nx-oss-magic:abracadabra\nx-oss-meta-author:foo@bar.com\n/oss-example/nelson

secretkey is:

	 OtxrzxIsfpFjA7SwPzILwy8Bw21TLhquhboDYROV

the expect value is:

	26NBxoKdsyly4EDv6inkoDft/yA=
	
I can confirm the value by bash or python.

but the value calculated by Paw(and all online calculator) is:

	erTe9B6jUm8KQmTQXa5l3BK6Ml8=

then I removed all `\n` in the input text:

	PUTODBGOERFMDMzQTczRUY3NUE3NzA5QzdFNUYzMDQxNEM=text/htmlThu, 17 Nov 2005 18:49:58 GMTx-oss-magic:abracadabrax-oss-meta-author:foo@bar.com/oss-example/nelson
	
now the calucated value of bash, python and Paw are same:

	6XwBalKWIXy3H1Vaae3Z4Sm6Aok=
	

After search on the web, I think Paw maybe processes the `\n` to the `\r\n` after pasting to the textfield.

below is  the sample code to verify
___

	
the python code to verify:

	import base64
	import hmac
	import sha
	h = hmac.new("OtxrzxIsfpFjA7SwPzILwy8Bw21TLhquhboDYROV",
	             "PUT\nODBGOERFMDMzQTczRUY3NUE3NzA5QzdFNUYzMDQxNEM=\ntext/html\nThu, 17 Nov 2005 18:49:58 GMT\nx-oss-magic:abracadabra\nx-oss-meta-author:foo@bar.com\n/oss-example/nelson", sha)
	print base64.encodestring(h.digest()).strip()

the bash code to verify:

	function hash_hmac {
	  digest="$1"
	  data="$2"
	  key="$3"
	  shift 3
	  echo -n "$data" | openssl dgst "-$digest" -hmac "$key" "$@"
	}
	
	
	hash_hmac "sha1" "PUT\nODBGOERFMDMzQTczRUY3NUE3NzA5QzdFNUYzMDQxNEM=\ntext/html\nThu, 17 Nov 2005 18:49:58 GMT\nx-oss-magic:abracadabra\nx-oss-meta-author:foo@bar.com\n/oss-example/nelson" "OtxrzxIsfpFjA7SwPzILwy8Bw21TLhquhboDYROV" -binary | base64

**Comment by mittsh** [comment]
@windirt sorry for the delay!!

So yes, it's bug. And no it isn't :) As input fields are interpreted by Paw as directly text, the `\n` isn't seen as a newline character but rather the 2 characters `\` + `n`. Other users had similar issues, so we're going to fix this. In the meantime, what you can do is to replace the `\n` by an actual newline which you can insert by hitting Option + Enter. It will visually look awkward, but the result will be correct.

![image](https://cloud.githubusercontent.com/assets/1319906/9987937/7785c676-604c-11e5-84a2-c39534c6d5c2.png)

Will keep the ticket open until we fix the `\n` issue.

**Comment by hishnash** [comment]
@windirt All fixed :) in v2.2.6.
We have added a dynamic value that represents the newline or (other escaped sequence).

![image](https://cloud.githubusercontent.com/assets/838127/11340724/a21ba538-91ff-11e5-82af-df97031d459e.png)


![image](https://cloud.githubusercontent.com/assets/838127/11340731/ae554552-91ff-11e5-9e28-1830dc72b522.png)

I will close this know, please let me know if you have any issues with this.

**Comment by mittsh** [comment]
Right! It's fixed now. You can also type `\n` preceded by a `{` and it will trigger the completion.
