### ISSUE TITLE
Add syntax highlighting & tree browse support for XML

### ISSUE THREAD

**Issue by modest** [luckymarmot/Paw-Issues#37]
For responses, JSON support is fantastic.  XML support is not.  Enough to switch to another product :(  Would love to see some love for XML.

**Comment by mittsh** [comment]
Yes, we will add syntax highlighting at first! Not sure about tree browse yet but we will keep it in mind.

**Comment by modest** [comment]
FYI, just XML syntax highlighting would be mostly sufficient for my scenarios – without tree browse – if the text field used "smart" soft wrapping like in Atom, to make it possible to visually follow the tree.

![Soft wrapping in Atom](https://cloud.githubusercontent.com/assets/990299/10479791/39a9563e-721b-11e5-8858-008081b79bef.png)

**Comment by mittsh** [comment]
@modest absolutely! the challenge is that there is no (good) native OS X library for this, the only way will be to use web-based stuff such as [Ace](https://ace.c9.io/)...

**Comment by drewish** [comment]
Worth noting the XML syntax highlighting has been working for a bit.

**Comment by mittsh** [comment]
Yep! I believe syntax highlighting is here since Paw 2.3 or something. Thanks @drewish! Closing.

**Comment by Gerst20051** [comment]
Curious what you ended up using to get XML syntax highlighting to work? @mittsh
