### ISSUE TITLE
Dynamic Value Extensions Only Run Once

### ISSUE THREAD

**Issue by vanvlack** [luckymarmot/Paw-Issues#38]
I noticed this today, when trying to run a request while using the [Random UUID Value](https://luckymarmot.com/paw/extensions/RandomUuidValue) and [Chance Dynamic Value](https://luckymarmot.com/paw/extensions/com.atan.ChanceDynamicValue) generators. If you use an extension which generates data multiple times in a request body, the generator is run once globally for the entire request.

Ideally, the generator extension would be called `N` times generating different values depending on how many times it was included. Example:

![image](https://cloud.githubusercontent.com/assets/190584/10618127/be1af004-7733-11e5-9e73-9315d258c8ef.png)

Generates:
```
curl -X "GET" "http://echo.luckymarmot.com" \
	-d $'{
 "first_uuid": "0223fff2-939c-478b-b2e7-013060197c9b",
 "second_uuid": "0223fff2-939c-478b-b2e7-013060197c9b",
 "third_uuid": "0223fff2-939c-478b-b2e7-013060197c9b"
}'
```

Expected:
```
curl -X "GET" "http://echo.luckymarmot.com" \
	-d $'{
 "first_uuid": "0223fff2-939c-478b-b2e7-013060197c9b",
 "second_uuid": "809cdc92-2d1b-41e1-960d-b97accf84845",
 "third_uuid": "e6ab0011-2f55-46f5-90c9-e54dc59aef54"
}'
```

**Comment by mittsh** [comment]
@vanvlack I see what you mean! this behavior is needed given our current implementation, though we would like to fix it at some point in the future...

In the meantime, what I suggest is that you generate your UUIDs with a JavaScript snippet:

![image](https://cloud.githubusercontent.com/assets/1319906/10691081/b17c9d5c-7986-11e5-8ba7-c5b7cb4f873d.png)

to insert a snippet, right-click and pick Extensions > Custom

the JS code is:

```javascript
function guid() {  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000)
      .toString(16)
      .substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
    s4() + '-' + s4() + s4() + s4();
}


function evaluate(context){
	return guid();
};
```

hope it helps!
