### ISSUE TITLE
Better documentation of DynamicValue

### ISSUE THREAD

**Issue by orclev** [luckymarmot/Paw-Issues#39]
In the documentation of DynamicValue it mentions that the native DynamicValue instances can be used with their identifiers and that the identifiers should be in the documentation, but I have been unable to find any mention of what those identifiers actually are. Additionally, even if the identifiers were provided it also doesn't specify what the required parameters would be for those DynamicValue objects (the second constructor parameter).

**Comment by mittsh** [comment]
I believe this is now fixed: https://luckymarmot.com/paw/doc/

We now have documentation for all dynamic values available:

* https://luckymarmot.com/paw/doc/dynamic-values/response
* https://luckymarmot.com/paw/doc/dynamic-values/request
* https://luckymarmot.com/paw/doc/dynamic-values/authorization
* https://luckymarmot.com/paw/doc/dynamic-values/cookies
* https://luckymarmot.com/paw/doc/dynamic-values/encoding_crypto
* https://luckymarmot.com/paw/doc/dynamic-values/utils
* https://luckymarmot.com/paw/doc/extensions/create-dynamic-value
