### ISSUE TITLE
Change encoding for web response

### ISSUE THREAD

**Issue by gbmksquare** [luckymarmot/Paw-Issues#41]
I am using Paw to test request for some web pages that are encoded with 'euc-kr'.
Non-english characters appear broken and I can't find an option to change the response encoding so that I can view the response as I would normally on a web browser.

**Comment by nfgrilo** [comment]
Hi!

Thanks for getting back to us, and sorry about the inconvenience!

I have been trying this with some pages using Korean charset (`euc-kr`), and Paw is rendering them correctly. See [this page](http://www.phpschool.com/gnuboard4/bbs/board.php?bo_table=qna_html&wr_id=125563) for example which correctly returns `Content-Type: text/html; charset=euc-kr`. It could be possible that the server serving your request may not be sending this info correctly. Could you please share with us an URL where you experience the issue?

PS: you can get back via support instead, if you not wish to share the URL publicly.

Thanks,

All the best,
Nuno

**Comment by gbmksquare** [comment]
I sent the link via your support page.

At the same time, I found that the page is returning `Content-Type: text/html;charSet=euc-kr`.

Thanks for your support.

**Comment by nfgrilo** [comment]
Thank you!

I will get back to you from support!

All the best,
Nuno

**Comment by mittsh** [comment]
For the record, we've just found (and fixed) the bug, it was because your server is setting `charSet` (with an uppercase `S`), while we were parsing it case-sensitive. It's now resolved on our local build, it will ship as part of Paw 2.3 in a week or so...

**Comment by gbmksquare** [comment]
Thanks! I will wait for the next release.
