### ISSUE TITLE
Joining arrays into comma separated strings

### ISSUE THREAD

**Issue by devboxr** [luckymarmot/Paw-Issues#48]
Hi there,

many APIs return something like this:

```json
[
  {
   "key": "a",
  },
  {
    "key": "b",
  },
  {
    "key": "c",
  },
]
```

I would like to take those values and create `a,b,c` out of them.

Is that something that is possible?

Also, love the new Paw and suggest my company to buy Paw for Teams!

Keep up the great work!

**Comment by devboxr** [comment]
Nevermind, just realised I can create a custom function :)
👍

**Comment by nunogoncalves** [comment]
@rebers how do you achieve that?
