### ISSUE TITLE
Add support for JsonPath filtering in response

### ISSUE THREAD

**Issue by maxromanovsky** [luckymarmot/Paw-Issues#52]
Details on JsonPath [here](https://github.com/jayway/JsonPath)

**Comment by mittsh** [comment]
Interesting! Yeah we'd love to add more path filtering options (like `jq`). This one seems interesting, we'll keep it in mind. Thanks!

**Comment by Gerst20051** [comment]
Similar To: https://github.com/luckymarmot/Paw-Issues/issues/53
