### ISSUE TITLE
Search in JSON view.

### ISSUE THREAD

**Issue by carlossless** [luckymarmot/Paw-Issues#53]
It would be cool if were able to not only search in the raw view of the request, but also in the structured JSON view. Navigating through large responses would become a lot easier.

**Comment by mittsh** [comment]
That's a good point @carlossless There's a "Filter by Key-Path" field at the bottom, but clearly isn't what you're looking for. I suppose, we could have a mode in which this field would effectively work as a search box.

**Comment by Gerst20051** [comment]
I agree with Roland here: https://stackoverflow.com/questions/36787672/paw-app-filtering-json-in-the-response-panel

Would be nice to be able to type in `jq` to search the json response.

**Comment by Gerst20051** [comment]
Similar To: https://github.com/luckymarmot/Paw-Issues/issues/52
