### ISSUE TITLE
Paw 3.2 not available on Setapp

### ISSUE THREAD

**Issue by mittalyashu** [luckymarmot/Paw-Issues#82]
Paw 3.2 is still not available via Setapp, showing older version.

![CleanShot 2020-10-21 at 10 34 50@2x](https://user-images.githubusercontent.com/29014463/96675686-12b17880-1389-11eb-88c8-2ec3702c9405.png)

**Comment by zakiaziz** [comment]
Should be coming to setapp this week: https://github.com/luckymarmot/Paw-Issues/issues/57#issuecomment-713706149

**Comment by mittalyashu** [comment]
Why the release date is out of sync, on the official site, the newer version is available for download but no update on Setapp

**Comment by JanC** [comment]
hi,
I was looking forward to having the GraphQL support but now I see it's still not released on Setapp. Any update on this?

**Comment by mittalyashu** [comment]
> Hi Yashu,
>
> We've sent the updated app yesterday to Setapp and it's being review so it'll take them a couple of days to accept and release.
> 
> Best,
> Piotr

Got a reply from support team.

**Comment by mittalyashu** [comment]
Paw 3.2 has been released.

![CleanShot 2020-10-27 at 08 48 16@2x](https://user-images.githubusercontent.com/29014463/97252931-2ea59600-1831-11eb-9764-140e95ca7294.png)
