### ISSUE TITLE
[Feature Request] Add Files on Mutation GraphQL like upload avatar or file pdf

### ISSUE THREAD

**Issue by harrytran998** [luckymarmot/Paw-Issues#91]
Because Paw dont have this feature, our team must switch another Client API `Altair GraphlQL Client`. Hope your team work for this!
![image](https://user-images.githubusercontent.com/24296018/97657219-e50cb380-1a9b-11eb-836d-17998daccc50.png)

**Comment by sebastiansson** [comment]
This would be awesome!

**Comment by franzwarning** [comment]
bump

**Comment by isaozler** [comment]
actually you can, use operations, map, and the file with incremental part name as multipart/form-data request

this is how we use it...

![image](https://user-images.githubusercontent.com/1378630/147391463-d7d0ed79-2c48-4ac5-a9da-e3e079460da8.png)

`--__X_PAW_BOUNDARY__
Content-Disposition: form-data; name="operations"

{"operationName":"createPost","variables":{"topic":"Topic","images":[{"image":null}],"tags":["123","321"]},"query":"mutation createPost($topic: String!, $images: [ImageUpload!]!, $tags: [String!]!) {\n  createPost(topic: $topic, images: $images, tags: $tags) {\n    id\n    __typename\n  }\n}"}
--__X_PAW_BOUNDARY__
Content-Disposition: form-data; name="map"

{"1":["variables.images.0.image"]}
--__X_PAW_BOUNDARY__
Content-Disposition: form-data; name="1"; filename="isaozler_vector.jpg"
Content-Type: image/jpeg
`

**Comment by pfcodes** [comment]
Would be great to have this as a native interface than having to do the operations, map, and file route
