### ISSUE TITLE
Endless loop on 401  with OAuth2 

### ISSUE THREAD

**Issue by micha149** [luckymarmot/Paw-Issues#99]
Hey there.

We are using OAuth2 authentication with the „Resource Owner password credentials” grant and the „Automatically get or refresh token” option enabled.

![Bildschirmfoto 2020-12-12 um 10 39 32](https://user-images.githubusercontent.com/298880/101980526-55dfe780-3c66-11eb-9ce8-944c6ddecb19.png)

When a request to an API endpoint is answered with code 401, paw loads a new access token from the token endpoint of our authentication server. But after this, it seems not to use this new token. Instead it repeats the API request with the old one, get again a 401 and loads a new access token. This ends up in an endless loop.

If I click the „Get Access Token” button and then „Use Access Token” manually, the API request will work fine.

**Comment by nunogoncalves** [comment]
Are you using 3.2? I found that 3.1 works, but 3.2 doesn't. So I actually had to settle on this. I also raised the issue on twitter but no answer until now. 

https://twitter.com/goncalvescmnuno/status/1350066090425114626?s=20

**Comment by lkeijmel** [comment]
I can confirm the same thing on 3.2. The only solution so far was downgrading back to 3.1

**Comment by lkeijmel** [comment]
I've mentioned it to support and got a reaction:

> Thanks again for contacting us and I'm really sorry to see this happening.
> 
> I've consulted your issue with the team and that particular one is being currently worked on. Our workaround if you are not a Big Sur user is to use the previous 3.1.10 version: http://paw.cloud/download/3.1.10 or get the token manually if you already upgraded to latest macOS.
> 
> Our team expects the fixed build to be shipped by the end of February and it will also contain the M1 native support. I can definitely see how frustrating this bug would be but I do hope the wait is worth its time.

**Comment by micha149** [comment]
Fixed in  3.2.1
